### PR TITLE
add license

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Comment by cyphar** [comment]
How about we add the standard license headers as comments to the `.yaml` files and grains?

**Comment by mssola** [comment]
Also, please add the header in the README.md file like we are doing for the other projects 😉

**Comment by jordimassaguerpla** [comment]
@cyphar : we've never added the license headers to yaml files ... I don't know the reason but I am guessing there must be.

**Comment by jordimassaguerpla** [comment]
@mssola : README contains now the license

**Comment by mssola** [comment]
> @cyphar : we've never added the license headers to yaml files ... I don't know the reason but I am guessing there must be one.

Actually there's none, and we should probably fix this in other repos 😄

**Comment by jordimassaguerpla** [comment]
@mssola : Where can I get an example of the "license headers"?

**Comment by jordimassaguerpla** [comment]
@mssola @cyphar : I added the license headers

**Comment by jordimassaguerpla** [comment]
@mssola @cyphar : does it look good?

**Comment by ereslibre** [comment]
I just wanted to add a comment here, `yaml` files are ok with a license, but maybe `conf` files is too much? Just my 2 cents here.

**Pull request merged**
