### PR TITLE
Removing hardcoded admin password for LDAP

### PR DESCRIPTION
**Pull request by robdaemon**

### CODE REVIEW

**Comment by robdaemon** [comment]
Depends-on: kubic-project/velum#301
Depends-on: kubic-project/salt#222
Depends-on: kubic-project/caasp-container-manifests#105

**Comment by robdaemon** [comment]
Also depends on IBS sles12sp3-openldap-image request 140541

**Comment by ereslibre** [comment]
Will test ASAP.

**Comment by kiall** [comment]
These work fine, however there is a issue with the ldap container entrypoint and escaping slashes, which seems to hit every few runs.

**Comment by kiall** [comment]
LDAP container fixed, working just fine now!

**Pull request merged**
