### PR TITLE
Use caasp v4 images

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
This needs to go together with https://github.com/kubic-project/salt/pull/747

**Comment by jordimassaguerpla** [comment]
@MaximilianMeister : will it be ok for you that we merge both Requests? I don't think  tests can pass separately...

**Comment by MalloZup** [comment]
https://github.com/SUSE/caasp-jenkins-library/pull/276

**Comment by MaximilianMeister** [comment]
> will it be ok for you that we merge both Requests? I don't think tests can pass separately...

yes, if you can force merge go ahead. image tags are all correct

**Comment by MaximilianMeister** [comment]
@jordimassaguerpla can we now do it without a patch? see https://github.com/kubic-project/caasp-container-manifests/pull/222

**Comment by MaximilianMeister** [comment]
now handeled in https://github.com/kubic-project/caasp-container-manifests/pull/222

**Pull request closed without merging**
