### PR TITLE
Several TLS fixes

### PR DESCRIPTION
**Pull request by kiall**
* Use different extensions when self signing the CA cert, and when signing end entity certs (removes CA:TRUE from end entity certs)
* Include a UUID in the CA's Subject field
* Include x509 Subject and Authority IDs in certs (This didn't actually fix bsc#1046881, but is good practice anyway as it allows for more reliable TLS chain validations)

bsc#1047177
bsc#1046881

### CODE REVIEW

**Comment by kiall** [comment]
CA Cert Before:

    Certificate:
        Data:
            Version: 1 (0x0)
            Serial Number:
                d0:15:65:40:5a:5f:4e:4e
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Internal, OU=CaaSP, CN=CaaSP Internal CA
            Validity
                Not Before: Jul  4 09:12:54 2017 GMT
                Not After : Jul  2 09:12:54 2027 GMT
            Subject: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Internal, OU=CaaSP, CN=CaaSP Internal CA
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (4096 bit)
                    Modulus:
                        00:d1:5e:98:35:10:af:c8:76:9e:9f:0c:26:e8:77:
                        b0:85:93:35:18:b7:e7:b5:02:cd:a9:c6:f2:cb:fa:
                        b6:d8:68:99:56:ce:4d:3a:4e:0a:61:34:2c:ba:14:
                        57:15:88:51:06:cf:fd:d9:37:3d:4e:7e:76:3a:e4:
                        ff:ec:0f:ed:ee:0e:be:eb:1c:fa:0b:23:c8:47:62:
                        a3:88:14:aa:e7:e5:49:3f:8c:9b:20:af:10:78:b7:
                        4c:6b:e5:13:66:ec:d1:cf:bc:a3:26:26:ff:18:2f:
                        b2:42:c3:16:f7:a3:7e:af:d8:e4:b7:c0:ef:77:ca:
                        7f:5a:fd:fd:2a:5f:fd:49:2f:d8:fc:aa:ed:5d:ed:
                        29:69:f9:1d:3b:6d:d6:3a:f6:00:97:85:20:4f:d2:
                        37:3c:07:41:0e:fe:fd:9b:8f:ef:6d:37:a4:17:67:
                        da:0a:be:75:f6:2b:f7:e4:79:d7:f1:c9:00:5e:24:
                        be:0e:80:dc:c8:db:4b:b6:d1:b2:92:35:d8:97:20:
                        be:d2:a9:aa:fc:b6:cd:b4:ff:79:50:7a:5f:58:09:
                        0e:18:07:55:46:25:34:71:06:60:a9:99:64:9a:ec:
                        b0:22:94:02:07:dc:af:6f:c5:4f:03:53:96:3c:4a:
                        13:ea:99:84:d3:a2:5e:68:59:c8:e6:93:c2:6f:1a:
                        3c:c2:e9:e9:f2:33:86:68:57:da:b6:1a:7c:00:50:
                        09:0f:d8:b7:eb:12:73:fc:56:07:66:e7:18:fe:ea:
                        09:eb:78:ea:68:c2:4a:3c:36:e2:39:6c:cc:ab:44:
                        e5:b1:ba:d7:4a:37:7a:85:4f:7b:bf:87:ce:15:9a:
                        f6:d1:2e:68:11:5a:32:50:71:5b:5f:a7:f7:0d:02:
                        fd:89:bf:a1:f6:ab:90:f8:7f:d4:42:46:3b:bc:a6:
                        b4:aa:cd:22:f9:81:51:d1:61:d7:d7:8a:3e:8d:4c:
                        46:e1:4e:5f:89:ad:b8:1c:20:92:64:5f:b8:f5:99:
                        0d:42:13:e1:00:65:3a:6d:8a:c7:19:f0:3a:d5:7f:
                        5a:60:99:c1:0b:ff:8d:fe:24:b3:7f:20:e3:73:be:
                        1a:e0:f7:03:ae:75:47:28:27:db:7b:da:0e:de:53:
                        c7:06:1d:3f:96:92:65:fe:e4:0f:39:d9:89:e4:91:
                        fa:f7:f1:5e:b0:aa:13:12:ac:25:ff:b4:ad:42:20:
                        da:0f:3d:a6:1f:a0:f1:67:5c:6c:76:a8:39:f2:59:
                        6b:bb:13:59:54:41:7a:1c:7a:f7:79:93:2b:66:1f:
                        94:2d:fe:6d:45:5e:c0:e6:38:5b:68:0b:1d:54:73:
                        98:7e:43:ea:cf:f8:ff:07:ab:50:f1:08:fd:e8:b4:
                        c3:5c:91
                    Exponent: 65537 (0x10001)
        Signature Algorithm: sha256WithRSAEncryption
             a6:b1:a8:ac:51:a9:bb:84:6e:9a:08:46:51:f7:1e:75:c2:75:
             d3:e5:99:69:2e:26:d9:0e:fd:d0:73:68:b6:8a:ab:8a:ce:20:
             ec:98:49:6c:12:c3:49:7d:a2:a0:2c:b1:dd:ad:60:57:a4:c1:
             95:c4:23:43:d7:ef:64:36:3a:e7:d6:a0:34:32:dc:81:b1:f1:
             cc:32:0d:6a:0c:07:78:fb:8e:ab:30:dd:f2:61:db:34:9a:52:
             1a:f4:c3:d1:63:9a:ac:6d:89:6f:f5:df:15:ca:43:6f:b6:a2:
             31:1f:43:84:7e:10:75:a6:15:3d:04:2b:0d:7d:23:d2:d8:40:
             4a:ef:89:0b:9b:fc:ba:7e:06:66:53:37:83:50:95:94:f4:ec:
             29:62:17:57:c4:81:23:cb:62:2c:15:ce:4a:48:04:be:bb:17:
             95:09:de:0c:27:45:22:8d:0a:2e:cd:57:41:e0:de:9f:9a:3f:
             c6:10:61:cc:1d:60:53:ea:a6:4c:eb:34:e6:98:53:a5:70:58:
             0d:49:6d:06:8e:d6:09:1d:3d:1d:df:7d:3f:b2:74:86:c9:07:
             af:82:b6:75:20:50:f8:a1:33:b4:15:fa:13:30:e4:15:5a:cf:
             99:1f:d1:23:16:33:af:c8:6f:11:99:f5:8a:03:d9:28:87:42:
             68:a7:52:6a:f8:6a:48:7d:3a:c8:9d:76:26:bb:a8:3d:d3:fe:
             75:a5:b5:b2:cc:a3:4c:34:d4:8c:8f:22:c8:43:6e:38:c4:65:
             fb:dd:54:70:9e:5d:c6:30:8c:c3:83:f2:ab:ae:c2:20:c6:c3:
             d1:fa:60:64:d3:c2:c2:d5:b4:5b:38:29:00:0f:67:4a:fb:6d:
             af:56:61:2c:4d:94:03:63:06:c5:57:9a:a7:1d:f4:54:b3:96:
             6b:00:d8:dc:0f:11:28:09:2c:bb:39:ec:71:56:d0:2f:39:68:
             bf:5b:51:0f:3e:21:1f:f6:dc:6f:c4:28:28:b7:4e:0a:e2:65:
             b8:52:ee:a7:da:64:8f:bb:4c:59:f9:63:bf:aa:dc:65:ec:2d:
             07:4b:67:35:37:b3:57:e5:07:10:94:94:b2:d2:5f:36:93:c4:
             8c:a1:68:fb:87:12:79:d0:f3:3f:9d:16:a9:6d:c9:91:cb:30:
             87:7e:83:f3:7a:8a:06:9c:67:4a:6f:8f:3e:03:84:80:8f:7a:
             c5:bb:1c:eb:74:69:33:d5:17:97:fe:5b:f4:9d:75:89:58:86:
             02:2b:48:23:cc:26:96:f8:5c:5d:21:c9:e7:82:f7:8b:65:02:
             53:79:a9:79:cd:41:71:a3:e7:96:f3:3a:17:38:29:7d:cd:f8:
             fd:09:cb:84:38:76:2b:c4

**Comment by kiall** [comment]
CA Cert After:

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number:
                b3:32:79:4a:25:61:ea:e5
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Internal, OU=CaaSP, CN=CaaSP Internal CA
            Validity
                Not Before: Jul  4 10:29:13 2017 GMT
                Not After : Jul  2 10:29:13 2027 GMT
            Subject: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Internal, OU=CaaSP, CN=CaaSP Internal CA
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (4096 bit)
                    Modulus:
                        00:b2:bb:91:6d:3b:c0:f2:cb:7b:17:3b:2c:35:43:
                        c8:b9:89:02:42:ce:cc:e2:a8:cf:1c:79:ae:b2:58:
                        e7:97:bb:25:71:16:ee:84:36:a3:ca:40:51:14:60:
                        6d:26:53:84:58:9c:fb:27:76:38:c1:4c:72:e6:1f:
                        da:54:d0:6b:ab:b8:9d:1c:32:9e:9a:7b:98:d6:ed:
                        bc:c6:40:ac:49:18:0c:9d:58:97:41:bc:6b:ee:37:
                        0e:64:a4:1c:e2:d9:01:35:92:58:cb:da:d4:53:81:
                        b1:3f:b8:66:82:92:cc:2a:82:89:8b:27:db:54:6d:
                        7c:25:14:07:2d:2f:d2:e4:e6:e1:73:7d:af:3b:37:
                        95:7a:7d:74:1a:eb:1d:b8:07:e3:6b:31:45:74:75:
                        ba:9e:09:cf:a2:ee:f7:ff:31:70:ad:6c:2a:d3:e6:
                        5a:ba:83:71:84:ca:fa:e0:67:09:32:39:88:4c:2b:
                        90:e5:40:ca:18:46:1d:86:8b:d3:73:e7:f3:b5:e5:
                        e0:71:95:66:d8:70:66:b0:46:e9:5f:b8:cc:1f:76:
                        69:38:0a:15:26:b8:14:2b:4f:3c:49:ba:fa:37:eb:
                        a5:91:d5:a0:35:f8:5b:f5:fc:2b:35:d3:00:3a:84:
                        6a:3d:95:32:80:ed:ef:f4:15:e2:1d:87:b5:8e:32:
                        b6:b7:68:c2:0d:81:62:4e:47:22:d1:1e:84:4f:0a:
                        fe:9d:c1:21:79:db:8d:62:d0:4b:f9:79:0b:e3:bd:
                        06:97:87:f8:84:42:20:05:f3:da:5d:eb:e1:ab:cf:
                        93:55:79:28:6a:d2:d8:81:ff:01:75:26:e7:7c:3e:
                        08:a8:4d:9e:11:fa:a4:6e:9b:18:14:ab:30:3c:f4:
                        2c:89:52:ac:f7:b4:1f:e1:31:1e:10:b4:d4:de:46:
                        b2:ab:0f:e1:9c:2e:4a:d9:d7:83:31:fb:c6:d9:44:
                        44:db:24:72:7d:05:73:51:25:5f:e8:a7:a9:a4:af:
                        cb:76:7e:cb:e0:73:35:c4:c4:a9:0c:1e:0d:8b:04:
                        cd:7f:ba:29:57:6c:3b:b2:92:5d:08:2b:72:17:25:
                        ae:2d:2d:33:83:14:a6:b2:e4:4c:64:80:c5:1f:42:
                        5f:d9:64:ee:97:cc:2c:a2:26:fd:fb:e8:ba:a1:ad:
                        8e:11:55:54:32:f6:ca:38:d7:50:67:de:ce:a1:22:
                        f4:64:04:94:58:e1:10:99:0a:db:fb:cf:53:a7:10:
                        a0:5f:59:57:c3:d5:8c:f6:8e:05:84:8b:8d:07:8a:
                        9d:aa:a5:07:35:ec:17:f7:e7:ef:59:e0:e3:27:f3:
                        b0:7c:f6:46:c5:70:c1:84:97:e9:8b:2c:a6:e6:58:
                        96:30:27
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Basic Constraints: critical
                    CA:TRUE
                X509v3 Key Usage: critical
                    Digital Signature, Non Repudiation, Key Encipherment, Certificate Sign
        Signature Algorithm: sha256WithRSAEncryption
             1b:ed:b9:5c:e5:93:08:fc:1c:6d:a0:cf:61:e5:a5:7c:08:13:
             d6:4c:c4:ff:90:2e:23:bb:c0:81:74:a2:98:93:74:0a:a3:0f:
             ad:bf:d4:df:2f:e0:63:ca:49:4d:08:2e:6e:f8:d0:38:9e:67:
             9f:e7:71:17:d6:79:7c:8b:2d:4a:b1:0a:58:d3:48:8c:59:32:
             4d:38:96:0e:1c:b6:9a:83:d2:0e:49:b1:14:bf:de:89:84:ed:
             e8:df:31:b7:ad:dd:df:71:74:32:d1:95:40:22:34:ac:cc:72:
             a1:d9:e5:7e:9d:ec:8d:30:4c:52:9c:ee:9e:74:05:99:a5:33:
             99:c1:2a:cc:e4:b7:30:3d:f1:c2:b3:4b:8b:74:c2:ec:ff:77:
             1c:21:f0:cb:ab:66:a9:63:6c:af:58:05:c5:9c:6b:71:22:21:
             b5:96:d9:eb:2e:f0:91:ca:bc:41:32:58:b5:45:02:31:f0:36:
             89:5d:5e:e8:e1:b1:43:6d:d3:f1:b5:5f:25:57:0b:cb:a6:2a:
             5e:e9:46:e4:47:f9:0e:92:fc:7d:bd:23:34:ca:62:14:38:69:
             e0:22:75:2e:7a:3f:5d:8f:15:5d:3c:44:f8:dd:64:15:6a:98:
             ef:cc:3c:2b:1e:91:bc:f8:19:85:52:90:10:5d:cc:44:3e:9f:
             de:f1:05:1b:51:56:3b:e2:5c:30:40:1c:a6:3c:5b:fd:22:00:
             7a:0d:84:70:2d:6c:07:72:c0:4d:c3:36:75:fa:8b:0d:f6:13:
             55:81:34:fb:ea:c6:b7:ac:55:8a:d3:f0:42:58:38:8c:c9:a6:
             20:d4:8a:da:62:ee:cb:41:d7:e3:89:96:67:35:06:02:23:e8:
             80:44:84:7e:9b:47:9d:d9:1b:7c:0c:3e:41:48:94:4e:aa:c0:
             85:ef:58:68:f9:8a:31:3c:7b:19:78:3d:0a:f6:a5:9c:00:8b:
             ea:4d:f3:44:f2:ac:43:f3:59:ed:a4:ff:1a:0f:76:51:00:5a:
             c8:63:d8:a5:f2:f8:5a:84:28:88:71:1b:c2:43:66:b2:e7:79:
             7c:9d:fe:fc:d5:44:b6:58:b4:37:ad:47:d2:e6:70:e3:50:58:
             d9:a0:3f:18:38:ef:07:31:49:77:6d:ec:16:44:51:2d:8d:d9:
             e6:96:d9:29:91:27:17:75:c4:88:c7:f5:b9:ad:a8:74:61:c6:
             73:01:9b:9b:c8:79:20:43:1d:bb:a0:18:7c:b2:10:7b:0e:b7:
             ff:33:35:68:ff:1c:ef:d3:c2:c5:2c:b8:72:f0:10:38:c5:12:
             6c:52:44:91:b8:35:7c:27:ed:b6:40:4d:88:2d:88:b4:67:77:
             1f:67:2e:5b:31:52:cd:b9

**Comment by kiall** [comment]
Velum After:

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 4096 (0x1000)
        Signature Algorithm: sha256WithRSAEncryption
            Issuer: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Internal, OU=CaaSP, CN=CaaSP Internal CA
            Validity
                Not Before: Jul  4 10:29:14 2017 GMT
                Not After : Jul  4 10:29:14 2018 GMT
            Subject: C=DE, ST=Bavaria, O=SUSE Internal, OU=CaaSP, CN=kiall-z620
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        00:c0:e7:21:04:bd:1d:c0:4a:aa:3c:14:7b:53:fd:
                        12:2e:ab:00:a1:a4:40:29:20:0f:6d:b8:f4:0e:2c:
                        af:86:73:01:fb:26:d2:26:c0:fd:3c:ed:0e:00:66:
                        33:18:c8:24:55:e4:ef:2c:33:b2:61:06:8d:f7:9b:
                        41:fe:58:1f:46:84:ce:1f:66:70:8a:67:1d:47:e8:
                        c7:08:b6:08:a0:23:a6:dc:74:14:89:5c:3d:33:3f:
                        bd:4d:83:fb:fb:73:f0:a2:41:0c:a2:f8:e9:2e:f9:
                        5b:4a:c0:63:52:55:76:50:4d:3f:64:63:82:a1:02:
                        7d:26:bf:84:ac:b3:71:f6:68:04:83:e6:ec:a6:b0:
                        f0:9d:1f:11:77:52:e8:91:de:04:83:49:ae:fe:c9:
                        b7:0a:d4:ef:aa:89:97:89:a5:7d:1c:c2:f5:1e:2f:
                        11:bc:a6:9e:f3:e5:a9:88:f4:d8:ee:d2:26:0b:9c:
                        06:33:34:b0:9c:80:ff:ad:6f:2a:cd:3f:e5:00:11:
                        dd:7f:2c:ae:74:4a:90:60:c9:54:40:9c:5a:dd:f8:
                        a3:f0:5c:0a:e7:f8:a3:32:ac:2f:52:60:cf:27:12:
                        61:8d:23:dd:16:80:42:a5:23:6f:ca:75:69:da:46:
                        a9:8e:c5:3a:56:c5:83:1d:4a:bb:2b:f7:be:96:08:
                        c0:2b
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Basic Constraints: 
                    CA:FALSE
                X509v3 Key Usage: 
                    Digital Signature, Non Repudiation, Key Encipherment
                X509v3 Subject Alternative Name: 
                    DNS:kiall-z620, DNS:kiall-z620.suse.de, IP Address:172.31.0.102, IP Address:172.17.0.1, IP Address:10.163.1.208
        Signature Algorithm: sha256WithRSAEncryption
             1a:4d:64:90:66:a8:1c:4f:48:2e:05:87:78:ce:da:c0:1c:08:
             77:6d:6f:dc:ed:c8:41:d0:18:6e:4f:28:30:2f:2b:4d:9e:c0:
             5c:ee:85:27:6a:a5:c0:9d:45:db:73:dc:9b:43:95:4b:cb:6b:
             01:dc:6a:6d:b3:c1:5f:48:ad:1c:95:a2:2a:75:c2:1a:ca:d8:
             07:da:82:04:59:a0:ae:bb:ae:89:e2:d0:2d:c7:54:45:10:ab:
             88:6a:8f:78:d4:ad:3f:c3:20:8f:72:7c:c6:19:f6:8f:71:08:
             51:ee:62:30:bd:fe:44:74:2e:ae:38:88:29:1e:df:89:8c:de:
             5b:af:e7:f7:84:c2:97:df:26:27:1b:28:02:e9:f7:d6:a1:3b:
             67:28:4f:49:44:27:92:99:42:8c:e7:0b:ff:e2:57:96:3f:59:
             c7:00:e0:a1:3d:a2:75:30:c4:86:7d:57:50:79:e4:9f:32:5d:
             b6:f6:ef:d2:79:82:0d:17:c1:28:78:60:00:31:d4:cf:7a:d6:
             92:a2:99:e5:5f:ab:d8:84:30:78:b8:eb:70:57:0c:57:ba:ac:
             d5:44:8d:c0:02:a1:cf:82:bc:ca:85:b3:9a:6f:c4:f1:a8:00:
             01:f6:21:69:7b:63:5d:75:2a:57:2d:89:ca:88:f0:e3:9d:f6:
             16:ea:11:a3:48:3d:78:08:cf:d8:cc:a5:53:05:13:11:69:e8:
             2f:15:4f:87:6d:db:40:5d:5e:fb:8c:04:70:52:e5:e6:df:e2:
             dd:65:cd:d3:5f:f6:d4:ed:1a:38:46:5d:f7:64:70:55:b1:31:
             02:4a:f6:37:9e:bf:5d:a9:c8:ce:f0:13:f2:1b:b9:c0:d2:91:
             a1:52:f7:4f:12:4b:2f:f6:10:89:16:9f:f3:f8:98:07:4b:97:
             a2:0f:8d:5d:7a:32:a0:c9:4a:be:14:cb:9f:77:25:a9:18:f4:
             bc:c1:f8:30:1c:e0:5b:bb:cf:5d:cb:a2:aa:2d:11:2c:f9:fd:
             c0:fd:ad:d7:e3:3e:42:45:58:73:dc:60:f6:5d:68:8a:10:c9:
             79:ea:fd:13:01:b8:9e:52:a3:e1:4a:b1:03:9d:aa:f2:00:aa:
             90:f1:f2:5e:e5:26:f3:f6:81:1f:c6:c7:ec:6a:4f:e6:98:69:
             a2:60:5f:9d:8d:07:9c:cb:3a:f3:2a:70:2f:82:76:ae:4a:65:
             5b:9d:34:33:60:8d:3d:ed:62:1a:d1:4d:8c:14:52:c0:77:28:
             d2:1b:d2:44:b3:b1:9f:88:5b:db:db:f7:21:82:0c:0c:fb:0a:
             dc:37:e6:cb:38:78:77:7c:4d:28:e9:62:39:37:4e:4d:11:cc:
             33:f4:3c:70:cf:95:00:31

**Comment by ereslibre** [comment]
I can also confirm that with this patch I get the `DN` of the `CA` modified every run:

```
etc/pki@master openssl x509 -in ca.crt -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            9d:72:1a:9c:70:a9:13:41
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Autogenerated, OU=CaaSP b1a9ed25-e418-4617-9d43-9cc5537f874e, CN=CaaSP Internal CA
```

Re-run `devenv`:

```
etc/pki@master openssl x509 -in ca.crt -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            d6:d5:82:31:df:e4:18:85
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=DE, ST=Bavaria, L=Nuremberg, O=SUSE Autogenerated, OU=CaaSP 4475bd64-8967-4c3f-9bd1-0f3ae990dc28, CN=CaaSP Internal CA
```

This will not of course avoid browsers to cache the `CA`, but by modifying a field of the `DN` we should avoid the cache from being used.

Going to check if the salt generated certificates contain the expected settings.

**Comment by ereslibre** [comment]
After running an orchestration, I can confirm:

```
minion0:~ # openssl x509 -in /etc/pki/minion.crt -noout -text
(snip)
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
```

**Pull request merged**
