### PR TITLE
[WIP] add pv-recycler-node image

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
@ereslibre : what about it now?

**Comment by ereslibre** [comment]
LGTM, maybe we should wait for others to dump their thoughts on this :smile:

**Comment by jordimassaguerpla** [comment]
Should we add the option here? https://github.com/kubic-project/salt/blob/master/salt/kubernetes-master/config.jinja and https://github.com/kubic-project/salt/blob/master/salt/kubernetes-minion/config.jinja

**Comment by ereslibre** [comment]
From what I can see, we do:

```
EnvironmentFile=/etc/kubernetes/config (ignore_errors=yes)
EnvironmentFile=/etc/kubernetes/controller-manager (ignore_errors=yes)
```

at the `kube-controller-manager.service`. Now that I see it actually [the comment here](https://github.com/kubic-project/salt/blob/master/salt/kubernetes-minion/config.jinja) isn't accurate, but yes, we need to adapt the flags [here](https://github.com/kubic-project/salt/blob/master/salt/kubernetes-master/config.jinja) to refer to the pv-recycler template that we are adding.

**Comment by mssola** [comment]
Note that this files *must* be present before starting the controller manager, and adding this manifest file in this repo assumes that Kubernetes is already running, which is contradictory. Therefore, this manifest file should go into the salt repo instead, where we'll provision the kubernetes master with this manifest, and add the flag to the controller manager as we used to do when we had SLE12 support.

**Comment by ereslibre** [comment]
Actually this package will come preinstalled with MicroOS, so this is a step before salt runs, but it makes sense to add it on salt level instead of here (I don't have a strong opinion on where to provide it).

**Comment by ereslibre** [comment]
Scratch that, you are absolutely right @mssola. This needs to be done at salt level.

**Comment by ereslibre** [comment]
It's better at salt level to make this work on opensuse deployments too, but for MicroOS it won't make a difference (the yaml will come preinstalled). +1 for moving it to our salt states.

**Comment by jordimassaguerpla** [comment]
https://github.com/kubic-project/salt/pull/19

**Pull request closed without merging**
